include:
      - project: 'ocs/cicd/parent'
        ref: parent-1.1.11
        file: '/.gitlab-ci.yml'

stages:
  - compile and test
  - acceptance
  - production
  - publish reports

default:
      image: maven:3.8-openjdk-17-slim

.testphase:
      only: 
      - external

.deploy:
      only: 
       - external

.golive:
      only: 
       - external

# Doesn't workd with Jav 17 right now
sonar:
      only: 
       - external

pages:
  extends: .job
  stage: publish reports
  dependencies: []
  allow_failure: true
  script:
    - mvn $MAVEN_CLI_OPTS site -Ddependency.locations.enabled=false
    - if [ -d target/site ]; then mv -f target/site public; else mkdir public; fi
    - for file in *; do if [ -d "$file"/target/site ]; then mv "$file"/target/site public/"$file"; fi; done
  when: always
  artifacts:
    paths:
      - public
  only:
    - next
  needs:
  - compile and unit test

         
