include:
      - project: 'ocs/cicd/parent'
        ref: parent-1.0.8
        file: '/.gitlab-ci.yml'

image: maven:3.6-jdk-17-slim

.testphase:
      only: 
      - external

.deploy:
      only: 
       - external

.golive:
      only: 
       - external
